language: node_js

before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "export SEQ_MYSQL_USER=root"
  - "export SEQ_PG_USER=postgres"
  - "export SEQ_PG_PW=postgres"
  - 'if [ "$SEQ_VERSION" ]; then npm install sequelize@^$SEQ_VERSION.0.0; fi'

script:
  - "npm run ci"

node_js:
  - "13"
  - "12"
  - "10"

branches:
  except:
    - /^v\d+\./

env:
  - DB=mysql DIALECT=mysql
  - DB=mysql DIALECT=postgres
  - DB=mysql DIALECT=postgres-native
  - DB=mysql DIALECT=sqlite
  - DB=mysql DIALECT=mariadb
  - DB=mysql DIALECT=mssql
  - DB=mysql DIALECT=mysql SEQ_VERSION=2
  - DB=mysql DIALECT=postgres SEQ_VERSION=2
  - DB=mysql DIALECT=postgres-native SEQ_VERSION=2
  - DB=mysql DIALECT=sqlite SEQ_VERSION=2
  - DB=mysql DIALECT=mariadb SEQ_VERSION=2
  - DB=mysql DIALECT=mssql SEQ_VERSION=2

matrix:
  fast_finish: true
  include:
    - node_js: "12"
      env: DB=mysql DIALECT=mysql COVERAGE=true
  allow_failures:
    - env: DB=mysql DIALECT=mysql COVERAGE=true

addons:
  postgresql: "9.3"
